### ISSUE TITLE
Make the component compatible with react 15.4.1

### ISSUE THREAD

**Issue by thinh76** [stikmanw/react-fullstory-component#1]
Is it possible to make the component compatible with react 15.4.1 to remove the following warnings when running npm install?

┬ UNMET PEER DEPENDENCY react@15.4.1
│ ├─┬ fbjs@0.8.6
│ │ ├── core-js@1.2.7
│ │ ├─┬ isomorphic-fetch@2.2.1
│ │ │ ├─┬ node-fetch@1.6.3
│ │ │ │ └─┬ encoding@0.1.12
│ │ │ │   └── iconv-lite@0.4.15
│ │ │ └── whatwg-fetch@2.0.1
│ │ ├─┬ promise@7.1.1
│ │ │ └── asap@2.0.5
│ │ └── ua-parser-js@0.7.12
│ └── loose-envify@1.3.0
├── react-addons-test-utils@15.4.1
├── react-dom@15.4.1
├── react-fullstory-component@1.3.0

And here is npm ls react gives

└── UNMET PEER DEPENDENCY react@15.4.1

npm ERR! peer dep missing: react@0.13.3, required by react-fullstory-component@1.3.0
npm ERR! code 1

**Comment by stikmanw** [comment]
Thanks for the contribution, I fixed the build and everything is live for use.
